# Generated by Django 6.0.3 on 2026-03-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Comunidad')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número (Ej: Dpto 101)')),
                ('nombre_propietario', models.CharField(max_length=100, verbose_name='Nombre del Propietario')),
                ('email_propietario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Propietario')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.comunidad', verbose_name='Comunidad')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['comunidad', 'numero'],
            },
        ),
    ]
